name: CI Linux

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-18.04
    container:
      image: debian:stable-slim

    steps:
    - uses: actions/checkout@v2
    - uses: Bogdanp/setup-racket@v0.8
      with:
        architecture: 'x64'
        distribution: 'minimal'
        variant: 'CS'
        version: '7.7'
    - run: make raclette
